server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/h136799711/spring-config-server.git
          search-paths: config-repo
          #uri: ${HOME}/Desktop/config